server:
    port: 8080

    servlet:
      jsp:
        init-parameters:
          development: true

logging:
        com.gjsyoung.iteach: DEBUG

spring:
    profiles:
       active: dev  # 激活本地配置

    datasource:     # linux地址
        url: jdbc:mysql://119.29.203.133:3306/gjsyoung?useSSL=false
        username: cairuojin
        password: 44052100
        driver-class-name: com.mysql.jdbc.Driver

#redis cluster
#    redis:
#        cluster:
#          nodes:
#          - 119.29.203.133:7001
#          - 119.29.203.133:7002
#          - 119.29.203.133:7003
#          - 119.29.203.133:7004
#          - 119.29.203.133:7005
#          - 119.29.203.133:7006
#        maxRedirects: 3
#        password:

    mvc:
        static:
          static-path-pattern: /**
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

    servlet:
        multipart:
            max-request-size: 100Mb
            max-file-size: 10Mb

    rabbitmq:
        host: 111.230.196.33    #windows rabbitmq
        port: 5672
        username: cairuojin
        password: 44052100
        publisher-confirms: true

mybatis:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: com.gjsyoung.iteach.domain #设置别名，xml上可以直接引用，不需要写全类的包路径
    configuration:
      map-underscore-to-camel-case: true  #开启驼峰命名映射，当resultType填写为实体类，而不是BaseResultMap的时候，不会导致有下划线的字段无法映射到对应的属性

#文件上传地址
UploadPath: 'C:\sofeware\GjsYoung\WEB-INF\classes\static\'

#上传的最大大小
server.max-http-header-size: 10000000

#Face++ 密钥私钥
APIKey: LK951u8Sv8pU7NgHi0i5-xylwN494vC1
APISecret: EGGBj1niNMgiQ8zX_0TFnjm88WROHObZ

# rabbitMQ config  发送短信队列
LogExchange: LogExchange
LogQueue: LogQueue
LogRoutingKey: LogRoutingKey

#是否为本地环境,0否 1是
Local: 0