server:
    port: 8080

    servlet:
      jsp:
        init-parameters:
          development: true

logging:
        com.example.WChatMonkey: DEBUG

spring:
    profiles:
       active: dev  # 激活本地配置

    datasource:
        url: jdbc:mysql://localhost:3306/gjsyoung?useSSL=false
        username: root
        password: 44052100
        driver-class-name: com.mysql.jdbc.Driver

    redis:         #本地redis
        database: 0 # Redis数据库索引（默认为0）
        host: localhost
        port: 6379
        password:

    mvc:
        static:
          static-path-pattern: /**
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

    servlet:
        multipart:
            max-request-size: 100Mb
            max-file-size: 10Mb

    rabbitmq:
        host: localhost
        port: 5672
        username: cairuojin
        password: 44052100
        publisher-confirms: true

mybatis:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: com.gjsyoung.iteach.domain
    configuration:
      map-underscore-to-camel-case: true

#文件上传地址
UploadPath: 'E:\YYYY\YaoShunYu\GjsYoung\out\production\resources\static\'

#上传的最大大小
server.max-http-header-size: 10000000

#Face++ 密钥私钥
APIKey: LK951u8Sv8pU7NgHi0i5-xylwN494vC1
APISecret: EGGBj1niNMgiQ8zX_0TFnjm88WROHObZ

# rabbitMQ config  发送短信队列
LogExchange: LogExchange
LogQueue: LogQueue
LogRoutingKey: LogRoutingKey

#是否为本地环境,0否 1是
Local: 1